---
title: "CAM: Extroversion and SwB"
author: "Zijun Ke & Xin Tong"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(metafor) # standard meta-analyses
library(xlsx) # read in .xlsx files
library(lavaan) # for CFA analysis
library(MASS) # for bayesian sampling
library(hbmem) # for bayesian sampling
library(truncnorm) # for bayesian sampling
library(coda) # for bayesian sampling
source('D:/Research/180307A/MetaR/RealData2/CAM_Funcs.R')
```

# Set working directory
```{r}
wd = 'D:/Research/180307A/MetaR/RealData2/'
setwd(wd)
```

# Read in data
```{r}
dall = read.xlsx('Data.xlsx',1)
head(dall)
```

# Data preparation
# A. Gather and orgainze necessary information regarding reliability and residual correlation
```{r}
Nstudy = nrow(dall) # number of primary studies

# Specify IlambdaX and IlambdaY
#-----------------------------------
# ind.L: IlambdaX and IlambdaY
# Personality measures: 1: self reports; 2: informant reports
ind.L.personality = rep(1,Nstudy)
ind.L.personality[dall$Personality.Rater == 'Informant'] = 2
# SWB meausres: 3: SWL self reports; 4: PA self reports; 5: NA- self reports
# 6: SWL informant reports; 7: PA informant reports; 8: NA- informant reports
ind.L.SWB = rep(3,Nstudy)
sel.informant = (dall$SWB.Rater == 'Informant')
sel.SWL = (dall$SWB.Measure=='SWL')
sel.SWL[which(dall$SWB.Measure == 'LSS')] = TRUE
sel.SWL[which(dall$SWB.Measure == 'LSI')] = TRUE
ind.L.SWB[sel.SWL*sel.informant==1] = 6
sel.PA = (dall$SWB.Measure=='PANA: PA')
sel.PA[which(dall$SWB.Measure == 'PA: Other')] = TRUE
ind.L.SWB[sel.PA] = 4
ind.L.SWB[sel.PA*sel.informant==1] = 7
sel.NA = (dall$SWB.Measure=='PANA: NA-')
#sel.NA[which(dall$SWB.Measure == 'NA-: Other')] = TRUE
ind.L.SWB[sel.NA] = 5
ind.L.SWB[sel.NA*sel.informant==1] = 8
ind.L = cbind(ind.L.personality, ind.L.SWB) # IlambdaX and IlambdaY

# Specify Iphi
#--------------------------------------------------------
# location of nonzero residuals
# 1: residal correlations between self-rated SWL and personality
# 2: residal correlations between self-rated PA and personality
# 3: residal correlations between self-rated NA- and personality
gphi = rep(0,Nstudy)
gphi[sel.SWL*(sel.informant==0)*(ind.L.personality==1)==1] = 1
gphi[sel.PA*(sel.informant==0)*(ind.L.personality==1)==1] = 2
gphi[sel.NA*(sel.informant==0)*(ind.L.personality==1)==1] = 3

cbind(ind.L,gphi)
```

# Data preparation
# B. Make informed guesses of reliability
```{r}
# Reliability estimates for personality (extroversion) measures
#--------------------------------------------------------------
# Data are from DeYoung (2006) JPSP
drel.per = read.xlsx('Data.xlsx',3)
var.names = drel.per$Variable
drel.per = as.matrix(drel.per[,-c(1,10)])
rownames(drel.per) = var.names
colnames(drel.per) = var.names
myM <- '
	E =~ L1*ES + L2*EP1 + L3*EP2 + L4*EP3
	Nn =~ L5*N_S + L6*N_P1 + L7*N_P2 + L8*N_P3
	ES ~~ N_S;EP1 ~~ N_P1;EP2 ~~ N_P2;EP3 ~~ N_P3;
'
fit = cfa(model = myM,sample.cov = drel.per,sample.nobs=483,std.lv = TRUE)
summary(fit)
sel.names = c('L1','L2')
#sel.names = c('L5','L6')
mu.L = coef(fit)[sel.names]
V.L = vcov(fit)[sel.names,sel.names]

# Reliability estimates for SWB (subjective well-being) measures
#-----------------------------------------------------------------
# Data are from Walker & Schimmack(2007) in Journal of Research in Personality
# Theretically, SWB contains three aspects: life satisfaction, positive affect and negative affect
# LS is commonly measured by SWL scale; the later two constructs are often measured by PANA scale
drel.swb = read.xlsx('Data.xlsx',4)
var.names = drel.swb$Variable
drel.swb = as.matrix(drel.swb[,-c(1,8)])
rownames(drel.swb) = var.names
colnames(drel.swb) = var.names
myM <- '
  SWB =~ L1*SWLS + L4*SWLI + L2*PAS + L5*PAI + L3*NA_S + L6*NA_I
  SWLS ~~ PAS; SWLS~~NA_S; PAS ~~ NA_S
  SWLI ~~ PAI; SWLI~~NA_I; PAI ~~ NA_I
  SWLS ~~ SWLI;PAS ~~ PAI; NA_S ~~ NA_I
  SWLS ~~ V1*SWLS;SWLI ~~ V1*SWLI;
  PAS ~~ V2*PAS;PAI ~~ V2*PAI;
  NA_S ~~ V3*NA_S;NA_I ~~ V3*NA_I;
'
fit = cfa(model = myM,sample.cov = drel.swb,sample.nobs=75,std.lv = TRUE)
summary(fit)
# Square root of reliabilities and their sampling covariance matrixc (uncertainty)
mu.L = c(mu.L,coef(fit)[paste('L',1:6,sep='')])
V.L = rbind(cbind(V.L,matrix(0,2,6)),
	cbind(matrix(0,6,2),vcov(fit)[paste('L',1:6,sep=''),paste('L',1:6,sep='')]))

# Assemble study reliability
#-------------------------------------
rri = mu.L[ind.L[,1]]*mu.L[ind.L[,2]] # reliability of the study
t1 = data.frame(ind.L,gphi,rri)
#write.xlsx(t1,'t1.xlsx', col.names=T, row.names=F)
t1
```

# Meta-analysis
# C. Estimate mean correlation and between-study heterogeneity
```{r}
#Data preparation
#--------------------------------
ri = dall$r # effect sizes
ni = dall$N # sample sizes
vi = (1-ri^2)^2/(ni-1) # sampling variances of effect sizes

# Bare-Bones
#---------------------------------------------------------
BB = rma(ri,vi,weights = ni,method  = 'HS' ) 
BB
seCI.metafor(BB) # compute the se and CI for between-study SD based on BB results

# Hunter-Schmidt
#---------------------------------------------------------
HS = rma(ri/rri,vi/(rri^2),weights = ni*(rri^2),method  = 'HS' ) # Hunter and Schmidt
HS
seCI.metafor(HS) # compute the se and CI for between-study SD based on HS results

# Proposed method: CAM
#-----------------------------------------------------------------
initials = list(rho0 = 0,V.rho = 0.01,Phi = rep(0.1,3),rhoi = ri)
# Specify the prior for residual correlation
# mu: vector of prior means 
# sigma: vector of prior variances
# The sequence is the same as that in gphi:
# 1: the residual correlation between between self-rated SWL and personality
# 2: for residal correlation between self-rated PA and personality
# 3: for residal correlation between self-rated NA- and personality
prior = list(Phi = list(mu = rep(0,3), sigma = rep(100,3))) # uninformative prior
CAM = cam(ri,ni,mu.L,V.L,ind.L,gphi,initials,nburnin=1,niter=10000,nthin=1,prior)
jpeg(file="TraceDensity1.jpeg",width = 520, height = 720)
plot(CAM$fit.coda[,c(1,3,4)])
dev.off()
out.res(CAM)

# HS with Cronbach's Alpha
#---------------------------------------------------------------
# missing alpha was imputed by mean alpha of the group where the measure was in
alpha = cbind(alpha.impute(dall$Personality.Alpha,ind.L[,1]),alpha.impute(dall$SWB.Alpha,ind.L[,2]))
rri.a = sqrt(alpha[,1]*alpha[,2]) # study reliability
HS.a = rma(ri/rri.a,vi/(rri.a^2),weights = ni*(rri.a^2),method  = 'HS' )  # Hunter and Schmidt
HS.a
seCI.metafor(HS.a)

# Proposed method with residual correlations allowed between self- and informant-ratings
#----------------------------------------------------------------------------------------
gphi[gphi==0] = 4 # now we have four groups of nonzero residual correlations
initials = list(rho0 = 0,V.rho = 0.01,Phi = c(rep(0.1,3),0),rhoi = ri)
# An informative prior N(0,0.0025) is given to the residual correlation between self- and informant-ratings
prior = list(Phi = list(mu = rep(0,4), sigma = c(rep(100,3),0.0025))) # informative prior for the last residual correlation
CAM = cam(ri,ni,mu.L,V.L,ind.L,gphi,initials,nburnin=1,niter=10000,nthin=1,prior)
out.res(CAM)

```
